### ISSUE TITLE
Sometimes the context is a view

### ISSUE THREAD

**Issue by ale-rt** [syslabcom/slc.clicktracker#1]
This will make the clicktracker to break (it fails in traversing to `@@plone_portal_state`).

```
2016-09-14 09:48:29 ERROR Zope.SiteErrorLog 1473839309.470.646766310623 http://localhost:8981/star/portal_registry/edit/@@clicktracker-callback
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module slc.clicktracker.browser.views, line 22, in __call__
AttributeError: 'SimpleViewClass from /home/ale/Code/plone/webwork.' object has no attribute 'restrictedTraverse'
Traceback (most recent call last):
  File "/home/ale/Code/plone/webwork.deployment/work/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/Publish.py", line 138, in publish
    request, bind=1)
  File "/home/ale/Code/plone/webwork.deployment/work/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/mapply.py", line 77, in mapply
    if debug is not None: return debug(object,args,context)
  File "/home/ale/Code/plone/webwork.deployment/work/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/Publish.py", line 48, in call_object
    result=apply(object,args) # Type s<cr> to step into published object.
  File "/home/ale/Code/plone/webwork.deployment/work/eggs/slc.clicktracker-0.3-py2.7.egg/slc/clicktracker/browser/views.py", line 22, in __call__
    member = self.context.restrictedTraverse(
```

**Comment by ale-rt** [comment]
Example  URL:
- http://localhost:8981/star/portal_registry/edit/Products.CMFPlone.interfaces.syndication.ISiteSyndicationSettings.default_enabled

**Comment by reinhardt** [comment]
In star we're using a different viewlet than the default slc.clicktracker one. Have you tried it in vanilla Plone? Do you know whether it's a star-only issue?

**Comment by ale-rt** [comment]
I did not, but the fix should be rather indipendent from it if we change this line:
- https://github.com/syslabcom/slc.clicktracker/blob/03a611a661daef259df1c941d7464dc050d1eff0/src/slc/clicktracker/browser/views.py#L22

to use plone.api.user.get_current().id.

**Comment by reinhardt** [comment]
Interesting. Yes, I suppose we want to do that anyway.
